<script lang="ts">
  /**
   * Every page's <head>, in one place.
   *
   * Before this, routes hand-wrote `<title>` and `<meta name="description">`
   * and nothing else. That left three things broken across the whole site:
   *
   *   - No Open Graph or Twitter tags at all, so a link shared to X, Discord,
   *     Slack, Facebook or iMessage rendered as a bare grey URL with no title,
   *     no description and no image.
   *   - No <link rel="canonical"> anywhere except /games/[appid], so the same
   *     page reached with a tracking query string looked like a separate URL
   *     to a crawler.
   *   - The site name was written out as the literal string
   *     "· Steam F2P Tracker" in 20 separate files.
   *
   * og:url and og:image MUST be absolute. Crawlers do not resolve relative
   * URLs, and during prerender `page.url.origin` is the internal
   * "http://sveltekit-prerender" host, so the origin has to be the constant -
   * not anything read off the request.
   */
  import { page } from "$app/state";
  import { SITE_ORIGIN } from "$lib/site";

  interface Props {
    /** Page title WITHOUT the site suffix. Pass "" on the home page, whose
     *  title is the site name alone. */
    title?: string;
    description: string;
    /** Root-relative path to a social image. The default card is generated by
     *  scripts/gen-icons.py. */
    image?: string;
    type?: "website" | "article";
    /** Sets robots noindex. For routes that must never be indexed. */
    noindex?: boolean;
    /** Structured data, already shaped. Serialised here. */
    jsonld?: Record<string, unknown>;
  }

  let {
    title = "",
    description,
    image = "/og.png",
    type = "website",
    noindex = false,
    jsonld,
  }: Props = $props();

  const SITE = "Steam F2P Tracker";

  const fullTitle = $derived(title ? `${title} · ${SITE}` : SITE);

  /** Origin + pathname only: query strings and hashes are never canonical.
   *  The root keeps its slash; every other path loses a trailing one, so
   *  /about and /about/ do not compete. */
  const canonical = $derived.by(() => {
    const p = page.url.pathname;
    return SITE_ORIGIN + (p === "/" ? "/" : p.replace(/\/+$/, ""));
  });

  const ogImage = $derived(SITE_ORIGIN + image);
</script>

<svelte:head>
  <title>{fullTitle}</title>
  <meta name="description" content={description} />
  <link rel="canonical" href={canonical} />
  {#if noindex}<meta name="robots" content="noindex, follow" />{/if}

  <meta property="og:type" content={type} />
  <meta property="og:site_name" content={SITE} />
  <meta property="og:title" content={fullTitle} />
  <meta property="og:description" content={description} />
  <meta property="og:url" content={canonical} />
  <meta property="og:image" content={ogImage} />
  <!-- Dimensions let a crawler lay out the card before it has fetched the
       image; without them some clients fall back to the small square card. -->
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt" content={fullTitle} />

  <!-- summary_large_image is what turns an X card from a thumbnail strip into
       the full-width image. No twitter:site/creator: every social handle now
       redirects through poli0981.dev/links/, so naming one here would
       contradict that. -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content={fullTitle} />
  <meta name="twitter:description" content={description} />
  <meta name="twitter:image" content={ogImage} />

  {#if jsonld}
    <!-- eslint-disable-next-line svelte/no-at-html-tags -- JSON.stringify
         output, not user HTML. The `<` escape stops a string value containing
         "</script>" from closing the block early. -->
    {@html `<script type="application/ld+json">${JSON.stringify(jsonld).replace(/</g, "\\u003c")}</script>`}
  {/if}
</svelte:head>
