"""Emit @font-face rules for only the subsets this app can render.

Fontsource ships one CSS file containing every subset (latin, latin-ext,
vietnamese, cyrillic, cyrillic-ext, greek). The unicode-range gates what a
BROWSER downloads, so the extra subsets cost a visitor nothing -- but they are
still emitted into dist/, embedded into the Tauri desktop binary and the APK,
and precached by the service worker. For an app whose locales are en and vi,
cyrillic + greek is 91 KB of the 308 KB font payload for scripts that can never
appear.

So: parse Fontsource's own CSS, keep the three subsets that can, and write the
result into src/fonts.css. Parsing rather than transcribing, because a
hand-copied unicode-range is a silent rendering bug.
"""
import io
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

WEB = "E:/2/web"
KEEP = ("latin", "latin-ext", "vietnamese")

# Longest first so "latin-ext" is tested before "latin".
ALL_SUBSETS = ("cyrillic-ext", "latin-ext", "greek-ext", "vietnamese",
               "cyrillic", "greek", "latin")

FONTS = [
    ("bricolage-grotesque", "Bricolage Grotesque Variable"),
    ("ibm-plex-sans", "IBM Plex Sans Variable"),
    ("jetbrains-mono", "JetBrains Mono Variable"),
]

BLOCK = re.compile(r"@font-face\s*\{(.*?)\}", re.S)


def field(body, name):
    m = re.search(name + r"\s*:\s*([^;]+);", body)
    return m.group(1).strip() if m else None


out = [
    "/*",
    " * GENERATED by scripts/gen-fontface.py -- do not hand-edit.",
    " *",
    " * Only latin, latin-ext and vietnamese. Fontsource's own index.css also",
    " * carries cyrillic, cyrillic-ext and greek, which this app cannot render:",
    " * the shipped locales are en and vi. Those three subsets were 91 KB of a",
    " * 308 KB payload -- irrelevant to a browser (unicode-range gates the",
    " * download) but embedded in the desktop binary and the APK, and precached",
    " * by the service worker, where nothing gates anything.",
    " *",
    " * unicode-range values are copied from Fontsource's CSS by the generator,",
    " * never by hand: a mistyped range is a silent rendering bug that only",
    " * shows up on the one character it drops.",
    " */",
    "",
]

total = 0
for pkg, family in FONTS:
    css_path = os.path.join(WEB, "node_modules", "@fontsource-variable", pkg, "wght.css")
    if not os.path.exists(css_path):
        css_path = os.path.join(WEB, "node_modules", "@fontsource-variable", pkg, "index.css")
    css = io.open(css_path, encoding="utf-8").read()

    kept = 0
    for body in BLOCK.findall(css):
        src = field(body, "src") or ""
        # Matched against a known list, longest first: a greedy regex reads
        # "...-latin-ext-wght-normal" as subset "ext" and silently drops
        # latin-ext, which is the subset carrying most European diacritics.
        subset = next(
            (s for s in ALL_SUBSETS if ("-" + s + "-wght-normal.woff2") in src),
            None,
        )
        if subset is None or subset not in KEEP:
            continue
        file_name = re.search(r"files/([^)\"']+\.woff2)", src).group(1)
        size = os.path.getsize(os.path.join(WEB, "node_modules", "@fontsource-variable", pkg, "files", file_name))
        total += size
        out += [
            "@font-face {",
            '  font-family: "' + family + '";',
            "  font-style: normal;",
            "  font-display: " + (field(body, "font-display") or "swap") + ";",
            "  font-weight: " + (field(body, "font-weight") or "100 900") + ";",
            '  src: url("@fontsource-variable/' + pkg + "/files/" + file_name + '") format("woff2-variations");',
            "  unicode-range: " + field(body, "unicode-range") + ";",
            "}",
            "",
        ]
        kept += 1
    print("  " + pkg + ": kept " + str(kept) + " of " + str(len(BLOCK.findall(css))) + " subsets")

io.open(os.path.join(WEB, "src", "fonts.css"), "w", encoding="utf-8", newline="\n").write("\n".join(out))
print("wrote src/fonts.css -- " + str(total) + " bytes of woff2 (" + str(round(total / 1024)) + " KB)")
