name : Check Dead Links
on :
  schedule : [ { cron : '0 4 1,6,11,16,21,26 * *' } ]
  workflow_dispatch :
permissions : { contents : write }
jobs :
  check :
    runs-on : ubuntu-latest
    steps :
      -
        uses : actions/checkout@v6
        with : { token : '${{ secrets.GH_TOKEN }}' }
      -
        uses : actions/setup-python@v6
        with : { python-version : '3.12' }
      -
        run : chmod +x ./bash/dead_links.sh && ./bash/dead_links.sh
