name : Migrate Schema v2.1
on :
  workflow_dispatch :
permissions : { contents : write }
jobs :
  migrate :
    runs-on : ubuntu-latest
    steps :
      -
        uses : actions/checkout@v6
        with : { token : '${{ secrets.GH_TOKEN }}' }
      -
        uses : actions/setup-python@v6
        with : { python-version : '3.14' }
      -
        run : chmod +x ./bash/migrate.sh && ./bash/migrate.sh
