name : Purge Unhealthy Games
on :
  schedule : [ { cron : '0 5 * * 1' } ]
  workflow_dispatch :
permissions : { contents : write }
jobs :
  purge :
    runs-on : ubuntu-latest
    steps :
      -
        uses : actions/checkout@v6
        with : { token : '${{ secrets.GH_TOKEN }}' }
      -
        uses : actions/setup-python@v6
        with : { python-version : '3.14' }
      -
        run : chmod +x ./bash/purge.sh && ./bash/purge.sh
        env : { STEAM_API_KEY : '${{ secrets.STEAM_API_KEY }}' }
