name: Top Online Leaderboard
on:
  schedule: [{cron: '0 3 * * 0,3,5'}]
  workflow_dispatch:
permissions: {contents: write}
jobs:
  leaderboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with: {token: '${{ secrets.GH_TOKEN }}'}
      - uses: actions/setup-python@v6
        with: {python-version: '3.14'}
      - run: chmod +x ./bash/online.sh && ./bash/online.sh
        env: {STEAM_API_KEY: '${{ secrets.STEAM_API_KEY }}'}
